pipeline {
	agent { 
  label 'slave1' 
  }
	tools {
	nodejs 'NodeJS'
	}
	stages {
    stage('preparing files') {
  parallel {
		stage('compressing js') {
			steps {
				sh "ls www/js | xargs -I@ uglifyjs -o www/min/@ --compress"
            }
            }
   		stage('compressing css') {
      			steps {
        sh "ls www/js | xargs -I@ clean-css www/js/@ -o www/min/@"
    }
    }
}
}
}
}
