pipeline {
	agent { 
  label 'slave1' 
  }
	tools {
	nodejs 'NodeJS'
	}
	stages {
    stage('preparing files') {
  parallel {
		stage('compressing js') {
			steps {
				sh "uglifyjs -o www/min/@ --compress"
            }
            }
   		stage('compressing css') {
      			steps {
        sh "ls www/css | xargs -I@ cleancss -o www/min/@"
    }
    }
}
}
	stage('archiving the results') {
		steps {
		sh "tar --exclude=.git --exclude=www/css --exclude=www/js -czvf Week2_CI/CD_tools/result.tar.gz ."
		}
	}
}
}
